-- Binance Gift Card redemption audit table (V4).
-- Contains no API keys, no full redemption codes, and no user data exports.
CREATE TABLE IF NOT EXISTS binance_giftcard_redemptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(24) NOT NULL DEFAULT '',
    user_id INT UNSIGNED NOT NULL,
    role_at_redeem VARCHAR(20) NOT NULL,
    code_fingerprint CHAR(64) NOT NULL,
    code_last4 CHAR(4) NOT NULL,
    external_uid VARCHAR(128) NOT NULL,
    reference_no VARCHAR(64) NULL,
    identity_no VARCHAR(64) NULL,
    token VARCHAR(32) NULL,
    token_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
    exchange_rate DECIMAL(18,8) NOT NULL DEFAULT 0,
    credit_currency CHAR(3) NOT NULL DEFAULT 'THB',
    credit_percent DECIMAL(6,2) NOT NULL DEFAULT 100,
    count_for_ranking TINYINT(1) NOT NULL DEFAULT 1,
    rank_bonus_enabled TINYINT(1) NOT NULL DEFAULT 0,
    credit_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'received',
    request_stage VARCHAR(40) NOT NULL DEFAULT 'received',
    api_code VARCHAR(32) NULL,
    api_message_safe VARCHAR(255) NULL,
    http_code SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    provider_message_safe VARCHAR(255) NULL,
    provider_requested_at DATETIME NULL,
    transaction_id BIGINT UNSIGNED NULL,
    attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    redeemed_at DATETIME NULL,
    credited_at DATETIME NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_giftcard_request_id (request_id),
    UNIQUE KEY uq_giftcard_code_fingerprint (code_fingerprint),
    UNIQUE KEY uq_giftcard_reference_no (reference_no),
    UNIQUE KEY uq_giftcard_identity_no (identity_no),
    UNIQUE KEY uq_giftcard_transaction (transaction_id),
    KEY idx_giftcard_user_time (user_id, requested_at),
    KEY idx_giftcard_status_time (status, requested_at),
    KEY idx_giftcard_requested (requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
